/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'balance' : IDL.Int,
  'displayName' : IDL.Text,
});
export const ApiConfig = IDL.Record({
  'activationFee' : IDL.Nat,
  'paymentMobileNumber' : IDL.Text,
  'merchantUpiId' : IDL.Text,
  'qrCodeBlobId' : IDL.Text,
});
export const ApiStatusResult = IDL.Record({
  'balance' : IDL.Int,
  'isActive' : IDL.Bool,
});
export const Time = IDL.Int;
export const MpinStatus = IDL.Record({
  'isSet' : IDL.Bool,
  'failedAttempts' : IDL.Nat,
  'lockedUntil' : IDL.Opt(Time),
});
export const PaymentSettings = IDL.Record({
  'phonePeNumber' : IDL.Text,
  'googlePayNumber' : IDL.Text,
  'paytmNumber' : IDL.Text,
  'upiId' : IDL.Text,
  'qrCodeBlobId' : IDL.Text,
  'announcementText' : IDL.Text,
  'bannerBlobId' : IDL.Text,
});
export const ApiActivationRequest = IDL.Record({
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : Time,
    'rejected' : Time,
  }),
  'timestamp' : Time,
  'proofBlobId' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const PendingApiActivation = IDL.Record({
  'request' : ApiActivationRequest,
  'user' : IDL.Principal,
});
export const DepositRequest = IDL.Record({
  'timestamp' : Time,
  'proofBlobId' : IDL.Text,
  'amount' : IDL.Int,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : Time,
  'rejected' : Time,
});
export const WithdrawalRequest = IDL.Record({
  'upiDetails' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Int,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'transactionType' : IDL.Variant({
    'withdraw' : IDL.Null,
    'p2pReceive' : IDL.Principal,
    'deposit' : IDL.Null,
    'p2pSend' : IDL.Principal,
  }),
  'timestamp' : Time,
  'amount' : IDL.Int,
  'associatedParty' : IDL.Opt(IDL.Principal),
});
export const ApiData = IDL.Record({
  'token' : IDL.Opt(IDL.Text),
  'activationRequests' : IDL.Vec(ApiActivationRequest),
  'isActive' : IDL.Bool,
});
export const ApiPaymentResult = IDL.Record({
  'newBalance' : IDL.Int,
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const MpinVerifyResult = IDL.Record({
  'attemptsLeft' : IDL.Nat,
  'success' : IDL.Bool,
  'lockedUntil' : IDL.Opt(Time),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'isRead' : IDL.Bool,
  'isGlobal' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'senderIsAdmin' : IDL.Bool,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatQueueEntry = IDL.Record({
  'user' : IDL.Principal,
  'mobileNumber' : IDL.Text,
  'joinedAt' : IDL.Int,
});
export const ChatQueueStatus = IDL.Record({
  'position' : IDL.Int,
  'isActive' : IDL.Bool,
  'queueLength' : IDL.Int,
  'mobileNumber' : IDL.Text,
});
export const AdminUserInfo = IDL.Record({
  'principalText' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
  'mpin' : IDL.Text,
  'balance' : IDL.Int,
  'isLocked' : IDL.Bool,
});

export const ActiveChatInfo = IDL.Record({
  'user' : IDL.Principal,
  'mobileNumber' : IDL.Text,
  'joinedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adjustBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'approveApiActivation' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'approveDeposit' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCallerUserProfile' : IDL.Func([], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
  'getApiStatus' : IDL.Func([IDL.Text], [ApiStatusResult], ['query']),
  'getBalance' : IDL.Func([], [IDL.Int], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMpinStatus' : IDL.Func([], [MpinStatus], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getPendingApiActivationRequests' : IDL.Func(
      [],
      [IDL.Vec(PendingApiActivation)],
      ['query'],
    ),
  'getPendingDepositRequests' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Vec(IDL.Tuple(DepositRequest, RequestStatus)),
          )
        ),
      ],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Vec(IDL.Tuple(WithdrawalRequest, RequestStatus)),
          )
        ),
      ],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserApiData' : IDL.Func([], [ApiData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserCredentials' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAsAdmin' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMobileHashRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'p2pTransfer' : IDL.Func([IDL.Principal, IDL.Int], [], []),
  'p2pTransferByMobile' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'processApiPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [ApiPaymentResult],
      [],
    ),
  'revokeApiToken' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMpin' : IDL.Func([IDL.Text], [], []),
  'setUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitApiActivationRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitDepositRequest' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'updateApiConfig' : IDL.Func([ApiConfig], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
  'verifyMpin' : IDL.Func([IDL.Text], [MpinVerifyResult], []),
  'verifyUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'markAllMessagesRead' : IDL.Func([], [], []),
  'sendGlobalMessage' : IDL.Func([IDL.Text], [], []),
  'saveAdminVisibleData' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminGetAllUserDetails' : IDL.Func([], [IDL.Vec(AdminUserInfo)], ['query']),
  'sendPersonalMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'joinChatQueue' : IDL.Func([IDL.Text], [ChatQueueStatus], []),
  'leaveChatQueue' : IDL.Func([], [], []),
  'getChatQueueStatus' : IDL.Func([], [ChatQueueStatus], ['query']),
  'sendChatMessage' : IDL.Func([IDL.Text], [], []),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getActiveChatInfo' : IDL.Func([], [IDL.Opt(ActiveChatInfo)], ['query']),
  'getChatQueueList' : IDL.Func([], [IDL.Vec(ChatQueueEntry)], ['query']),
  'adminSendChatMessage' : IDL.Func([IDL.Text], [], []),
  'endCurrentChat' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'balance' : IDL.Int,
    'displayName' : IDL.Text,
  });
  const ApiConfig = IDL.Record({
    'activationFee' : IDL.Nat,
    'paymentMobileNumber' : IDL.Text,
    'merchantUpiId' : IDL.Text,
    'qrCodeBlobId' : IDL.Text,
  });
  const ApiStatusResult = IDL.Record({
    'balance' : IDL.Int,
    'isActive' : IDL.Bool,
  });
  const Time = IDL.Int;
  const MpinStatus = IDL.Record({
    'isSet' : IDL.Bool,
    'failedAttempts' : IDL.Nat,
    'lockedUntil' : IDL.Opt(Time),
  });
  const PaymentSettings = IDL.Record({
    'phonePeNumber' : IDL.Text,
    'googlePayNumber' : IDL.Text,
    'paytmNumber' : IDL.Text,
    'upiId' : IDL.Text,
    'qrCodeBlobId' : IDL.Text,
    'announcementText' : IDL.Text,
    'bannerBlobId' : IDL.Text,
  });
  const ApiActivationRequest = IDL.Record({
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : Time,
      'rejected' : Time,
    }),
    'timestamp' : Time,
    'proofBlobId' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const PendingApiActivation = IDL.Record({
    'request' : ApiActivationRequest,
    'user' : IDL.Principal,
  });
  const DepositRequest = IDL.Record({
    'timestamp' : Time,
    'proofBlobId' : IDL.Text,
    'amount' : IDL.Int,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : Time,
    'rejected' : Time,
  });
  const WithdrawalRequest = IDL.Record({
    'upiDetails' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Int,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'transactionType' : IDL.Variant({
      'withdraw' : IDL.Null,
      'p2pReceive' : IDL.Principal,
      'deposit' : IDL.Null,
      'p2pSend' : IDL.Principal,
    }),
    'timestamp' : Time,
    'amount' : IDL.Int,
    'associatedParty' : IDL.Opt(IDL.Principal),
  });
  const ApiData = IDL.Record({
    'token' : IDL.Opt(IDL.Text),
    'activationRequests' : IDL.Vec(ApiActivationRequest),
    'isActive' : IDL.Bool,
  });
  const ApiPaymentResult = IDL.Record({
    'newBalance' : IDL.Int,
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const MpinVerifyResult = IDL.Record({
    'attemptsLeft' : IDL.Nat,
    'success' : IDL.Bool,
    'lockedUntil' : IDL.Opt(Time),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'isRead' : IDL.Bool,
    'isGlobal' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'senderIsAdmin' : IDL.Bool,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatQueueEntry = IDL.Record({
    'user' : IDL.Principal,
    'mobileNumber' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  const ChatQueueStatus = IDL.Record({
    'position' : IDL.Int,
    'isActive' : IDL.Bool,
    'queueLength' : IDL.Int,
    'mobileNumber' : IDL.Text,
  });
  const AdminUserInfo = IDL.Record({
    'principalText' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'mpin' : IDL.Text,
    'balance' : IDL.Int,
    'isLocked' : IDL.Bool,
  });
  const ActiveChatInfo = IDL.Record({
    'user' : IDL.Principal,
    'mobileNumber' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adjustBalance' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'approveApiActivation' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'approveDeposit' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCallerUserProfile' : IDL.Func([], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getApiConfig' : IDL.Func([], [ApiConfig], ['query']),
    'getApiStatus' : IDL.Func([IDL.Text], [ApiStatusResult], ['query']),
    'getBalance' : IDL.Func([], [IDL.Int], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMpinStatus' : IDL.Func([], [MpinStatus], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getPendingApiActivationRequests' : IDL.Func(
        [],
        [IDL.Vec(PendingApiActivation)],
        ['query'],
      ),
    'getPendingDepositRequests' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Vec(IDL.Tuple(DepositRequest, RequestStatus)),
            )
          ),
        ],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Vec(IDL.Tuple(WithdrawalRequest, RequestStatus)),
            )
          ),
        ],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserApiData' : IDL.Func([], [ApiData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserCredentials' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAsAdmin' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMobileHashRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'p2pTransfer' : IDL.Func([IDL.Principal, IDL.Int], [], []),
    'p2pTransferByMobile' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'processApiPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [ApiPaymentResult],
        [],
      ),
    'revokeApiToken' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMpin' : IDL.Func([IDL.Text], [], []),
    'setUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitApiActivationRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitDepositRequest' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'submitWithdrawalRequest' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'updateApiConfig' : IDL.Func([ApiConfig], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updatePaymentSettings' : IDL.Func([PaymentSettings], [], []),
    'verifyMpin' : IDL.Func([IDL.Text], [MpinVerifyResult], []),
    'verifyUserCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'markAllMessagesRead' : IDL.Func([], [], []),
    'sendGlobalMessage' : IDL.Func([IDL.Text], [], []),
    'saveAdminVisibleData' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminGetAllUserDetails' : IDL.Func([], [IDL.Vec(AdminUserInfo)], ['query']),
    'sendPersonalMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'joinChatQueue' : IDL.Func([IDL.Text], [ChatQueueStatus], []),
    'leaveChatQueue' : IDL.Func([], [], []),
    'getChatQueueStatus' : IDL.Func([], [ChatQueueStatus], ['query']),
    'sendChatMessage' : IDL.Func([IDL.Text], [], []),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getActiveChatInfo' : IDL.Func([], [IDL.Opt(ActiveChatInfo)], ['query']),
    'getChatQueueList' : IDL.Func([], [IDL.Vec(ChatQueueEntry)], ['query']),
    'adminSendChatMessage' : IDL.Func([IDL.Text], [], []),
    'endCurrentChat' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
