/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiActivationRequest {
  'status' : { 'pending' : null } |
    { 'approved' : Time } |
    { 'rejected' : Time },
  'timestamp' : Time,
  'proofBlobId' : string,
  'transactionId' : string,
}
export interface ApiConfig {
  'activationFee' : bigint,
  'paymentMobileNumber' : string,
  'merchantUpiId' : string,
  'qrCodeBlobId' : string,
}
export interface ApiData {
  'token' : [] | [string],
  'activationRequests' : Array<ApiActivationRequest>,
  'isActive' : boolean,
}
export interface ApiPaymentResult {
  'newBalance' : bigint,
  'message' : string,
  'success' : boolean,
}
export interface ApiStatusResult { 'balance' : bigint, 'isActive' : boolean }
export interface DepositRequest {
  'timestamp' : Time,
  'proofBlobId' : string,
  'amount' : bigint,
}
export interface MpinStatus {
  'isSet' : boolean,
  'failedAttempts' : bigint,
  'lockedUntil' : [] | [Time],
}
export interface MpinVerifyResult {
  'attemptsLeft' : bigint,
  'success' : boolean,
  'lockedUntil' : [] | [Time],
}
export interface PaymentSettings {
  'phonePeNumber' : string,
  'googlePayNumber' : string,
  'paytmNumber' : string,
  'upiId' : string,
  'qrCodeBlobId' : string,
}
export interface PendingApiActivation {
  'request' : ApiActivationRequest,
  'user' : Principal,
}
export type RequestStatus = { 'pending' : null } |
  { 'approved' : Time } |
  { 'rejected' : Time };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'transactionType' : { 'withdraw' : null } |
    { 'p2pReceive' : Principal } |
    { 'deposit' : null } |
    { 'p2pSend' : Principal },
  'timestamp' : Time,
  'amount' : bigint,
  'associatedParty' : [] | [Principal],
}
export interface UserProfile { 'balance' : bigint, 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'upiDetails' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adjustBalance' : ActorMethod<[Principal, bigint], undefined>,
  'approveApiActivation' : ActorMethod<[Principal, boolean], undefined>,
  'approveDeposit' : ActorMethod<[Principal, bigint, boolean], undefined>,
  'approveWithdrawal' : ActorMethod<[Principal, bigint, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getApiConfig' : ActorMethod<[], ApiConfig>,
  'getApiStatus' : ActorMethod<[string], ApiStatusResult>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMpinStatus' : ActorMethod<[], MpinStatus>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getPendingApiActivationRequests' : ActorMethod<
    [],
    Array<PendingApiActivation>
  >,
  'getPendingDepositRequests' : ActorMethod<
    [],
    Array<[Principal, Array<[DepositRequest, RequestStatus]>]>
  >,
  'getPendingWithdrawalRequests' : ActorMethod<
    [],
    Array<[Principal, Array<[WithdrawalRequest, RequestStatus]>]>
  >,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getTransactionHistory' : ActorMethod<[Principal], Array<Transaction>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserApiData' : ActorMethod<[], ApiData>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserCredentials' : ActorMethod<[], boolean>,
  'initializeAsAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'p2pTransfer' : ActorMethod<[Principal, bigint], undefined>,
  'processApiPayment' : ActorMethod<[string, bigint, string], ApiPaymentResult>,
  'revokeApiToken' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setMpin' : ActorMethod<[string], undefined>,
  'isMobileHashRegistered' : ActorMethod<[string], boolean>,
  'setUserCredentials' : ActorMethod<[string, string], undefined>,
  'submitApiActivationRequest' : ActorMethod<[string, string], undefined>,
  'submitDepositRequest' : ActorMethod<[bigint, string], undefined>,
  'submitWithdrawalRequest' : ActorMethod<[bigint, string], undefined>,
  'updateApiConfig' : ActorMethod<[ApiConfig], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updatePaymentSettings' : ActorMethod<[PaymentSettings], undefined>,
  'verifyMpin' : ActorMethod<[string], MpinVerifyResult>,
  'verifyUserCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];