/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApiStatusResult {
    balance: bigint;
    isActive: boolean;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type RequestStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: Time;
} | {
    __kind__: "rejected";
    rejected: Time;
};
export interface MpinVerifyResult {
    attemptsLeft: bigint;
    success: boolean;
    lockedUntil?: Time;
}
export interface MpinStatus {
    isSet: boolean;
    failedAttempts: bigint;
    lockedUntil?: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ApiConfig {
    activationFee: bigint;
    paymentMobileNumber: string;
    merchantUpiId: string;
    qrCodeBlobId: string;
}
export interface Transaction {
    id: string;
    status: Variant_pending_approved_rejected;
    transactionType: {
        __kind__: "withdraw";
        withdraw: null;
    } | {
        __kind__: "p2pReceive";
        p2pReceive: Principal;
    } | {
        __kind__: "deposit";
        deposit: null;
    } | {
        __kind__: "p2pSend";
        p2pSend: Principal;
    };
    timestamp: Time;
    amount: bigint;
    associatedParty?: Principal;
}
export interface PendingApiActivation {
    request: ApiActivationRequest;
    user: Principal;
}
export interface PaymentSettings {
    phonePeNumber: string;
    googlePayNumber: string;
    paytmNumber: string;
    upiId: string;
    qrCodeBlobId: string;
}
export interface ApiData {
    token?: string;
    activationRequests: Array<ApiActivationRequest>;
    isActive: boolean;
}
export interface ApiActivationRequest {
    status: {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "approved";
        approved: Time;
    } | {
        __kind__: "rejected";
        rejected: Time;
    };
    timestamp: Time;
    proofBlobId: string;
    transactionId: string;
}
export interface DepositRequest {
    timestamp: Time;
    proofBlobId: string;
    amount: bigint;
}
export interface ApiPaymentResult {
    newBalance: bigint;
    message: string;
    success: boolean;
}
export interface WithdrawalRequest {
    upiDetails: string;
    timestamp: Time;
    amount: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    balance: bigint;
    displayName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adjustBalance(user: Principal, newBalance: bigint): Promise<void>;
    approveApiActivation(user: Principal, approved: boolean): Promise<void>;
    approveDeposit(user: Principal, index: bigint, approved: boolean): Promise<void>;
    approveWithdrawal(user: Principal, index: bigint, approved: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCallerUserProfile(): Promise<void>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getApiConfig(): Promise<ApiConfig>;
    getApiStatus(token: string): Promise<ApiStatusResult>;
    getBalance(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMpinStatus(): Promise<MpinStatus>;
    getPaymentSettings(): Promise<PaymentSettings>;
    getPendingApiActivationRequests(): Promise<Array<PendingApiActivation>>;
    getPendingDepositRequests(): Promise<Array<[Principal, Array<[DepositRequest, RequestStatus]>]>>;
    getPendingWithdrawalRequests(): Promise<Array<[Principal, Array<[WithdrawalRequest, RequestStatus]>]>>;
    getProfile(profileOwner: Principal): Promise<UserProfile | null>;
    getTransactionHistory(user: Principal): Promise<Array<Transaction>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserApiData(): Promise<ApiData>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserCredentials(): Promise<boolean>;
    initializeAsAdmin(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    p2pTransfer(to: Principal, amount: bigint): Promise<void>;
    processApiPayment(token: string, amount: bigint, number: string): Promise<ApiPaymentResult>;
    revokeApiToken(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMpin(mpinHash: string): Promise<void>;
    isMobileHashRegistered(mobileHash: string): Promise<boolean>;
    setUserCredentials(mobileHash: string, passwordHash: string): Promise<void>;
    submitApiActivationRequest(proofBlobId: string, transactionId: string): Promise<void>;
    submitDepositRequest(amount: bigint, proofBlobId: string): Promise<void>;
    submitWithdrawalRequest(amount: bigint, upiDetails: string): Promise<void>;
    updateApiConfig(newConfig: ApiConfig): Promise<void>;
    updateDisplayName(newName: string): Promise<void>;
    updatePaymentSettings(newSettings: PaymentSettings): Promise<void>;
    verifyMpin(mpinHash: string): Promise<MpinVerifyResult>;
    verifyUserCredentials(mobileHash: string, passwordHash: string): Promise<boolean>;
}
import type { ApiActivationRequest as _ApiActivationRequest, ApiData as _ApiData, DepositRequest as _DepositRequest, MpinStatus as _MpinStatus, MpinVerifyResult as _MpinVerifyResult, PendingApiActivation as _PendingApiActivation, RequestStatus as _RequestStatus, Time as _Time, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adjustBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustBalance(arg0, arg1);
            return result;
        }
    }
    async approveApiActivation(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApiActivation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApiActivation(arg0, arg1);
            return result;
        }
    }
    async approveDeposit(arg0: Principal, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0, arg1, arg2);
            return result;
        }
    }
    async approveWithdrawal(arg0: Principal, arg1: bigint, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCallerUserProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerUserProfile();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getApiConfig(): Promise<ApiConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiConfig();
            return result;
        }
    }
    async getApiStatus(arg0: string): Promise<ApiStatusResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiStatus(arg0);
            return result;
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMpinStatus(): Promise<MpinStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMpinStatus();
                return from_candid_MpinStatus_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMpinStatus();
            return from_candid_MpinStatus_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSettings(): Promise<PaymentSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSettings();
            return result;
        }
    }
    async getPendingApiActivationRequests(): Promise<Array<PendingApiActivation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingApiActivationRequests();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingApiActivationRequests();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingDepositRequests(): Promise<Array<[Principal, Array<[DepositRequest, RequestStatus]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingDepositRequests();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingDepositRequests();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawalRequests(): Promise<Array<[Principal, Array<[WithdrawalRequest, RequestStatus]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawalRequests();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawalRequests();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(arg0: Principal): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserApiData(): Promise<ApiData> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserApiData();
                return from_candid_ApiData_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserApiData();
            return from_candid_ApiData_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserCredentials(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserCredentials();
            return result;
        }
    }
    async initializeAsAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAsAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async p2pTransfer(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.p2pTransfer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.p2pTransfer(arg0, arg1);
            return result;
        }
    }
    async processApiPayment(arg0: string, arg1: bigint, arg2: string): Promise<ApiPaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processApiPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processApiPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async revokeApiToken(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeApiToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeApiToken(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setMpin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMpin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMpin(arg0);
            return result;
        }
    }
    async isMobileHashRegistered(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMobileHashRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMobileHashRegistered(arg0);
            return result;
        }
    }
    async setUserCredentials(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserCredentials(arg0, arg1);
            return result;
        }
    }
    async submitApiActivationRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApiActivationRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApiActivationRequest(arg0, arg1);
            return result;
        }
    }
    async submitDepositRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositRequest(arg0, arg1);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async updateApiConfig(arg0: ApiConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApiConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApiConfig(arg0);
            return result;
        }
    }
    async updateDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDisplayName(arg0);
            return result;
        }
    }
    async updatePaymentSettings(arg0: PaymentSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentSettings(arg0);
            return result;
        }
    }
    async verifyMpin(arg0: string): Promise<MpinVerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMpin(arg0);
                return from_candid_MpinVerifyResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMpin(arg0);
            return from_candid_MpinVerifyResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyUserCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUserCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUserCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApiActivationRequest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiActivationRequest): ApiActivationRequest {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ApiData_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiData): ApiData {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_MpinStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MpinStatus): MpinStatus {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MpinVerifyResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MpinVerifyResult): MpinVerifyResult {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PendingApiActivation_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingApiActivation): PendingApiActivation {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isSet: boolean;
    failedAttempts: bigint;
    lockedUntil: [] | [_Time];
}): {
    isSet: boolean;
    failedAttempts: bigint;
    lockedUntil?: Time;
} {
    return {
        isSet: value.isSet,
        failedAttempts: value.failedAttempts,
        lockedUntil: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.lockedUntil))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: _ApiActivationRequest;
    user: Principal;
}): {
    request: ApiActivationRequest;
    user: Principal;
} {
    return {
        request: from_candid_ApiActivationRequest_n19(_uploadFile, _downloadFile, value.request),
        user: value.user
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: _Time;
    } | {
        rejected: _Time;
    };
    timestamp: _Time;
    proofBlobId: string;
    transactionId: string;
}): {
    status: {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "approved";
        approved: Time;
    } | {
        __kind__: "rejected";
        rejected: Time;
    };
    timestamp: Time;
    proofBlobId: string;
    transactionId: string;
} {
    return {
        status: from_candid_variant_n21(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        proofBlobId: value.proofBlobId,
        transactionId: value.transactionId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    transactionType: {
        withdraw: null;
    } | {
        p2pReceive: Principal;
    } | {
        deposit: null;
    } | {
        p2pSend: Principal;
    };
    timestamp: _Time;
    amount: bigint;
    associatedParty: [] | [Principal];
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    transactionType: {
        __kind__: "withdraw";
        withdraw: null;
    } | {
        __kind__: "p2pReceive";
        p2pReceive: Principal;
    } | {
        __kind__: "deposit";
        deposit: null;
    } | {
        __kind__: "p2pSend";
        p2pSend: Principal;
    };
    timestamp: Time;
    amount: bigint;
    associatedParty?: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_variant_n35(_uploadFile, _downloadFile, value.transactionType),
        timestamp: value.timestamp,
        amount: value.amount,
        associatedParty: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.associatedParty))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: [] | [string];
    activationRequests: Array<_ApiActivationRequest>;
    isActive: boolean;
}): {
    token?: string;
    activationRequests: Array<ApiActivationRequest>;
    isActive: boolean;
} {
    return {
        token: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.token)),
        activationRequests: from_candid_vec_n40(_uploadFile, _downloadFile, value.activationRequests),
        isActive: value.isActive
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attemptsLeft: bigint;
    success: boolean;
    lockedUntil: [] | [_Time];
}): {
    attemptsLeft: bigint;
    success: boolean;
    lockedUntil?: Time;
} {
    return {
        attemptsLeft: value.attemptsLeft,
        success: value.success,
        lockedUntil: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.lockedUntil))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<[_DepositRequest, _RequestStatus]>]): [Principal, Array<[DepositRequest, RequestStatus]>] {
    return [
        value[0],
        from_candid_vec_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_DepositRequest, _RequestStatus]): [DepositRequest, RequestStatus] {
    return [
        value[0],
        from_candid_RequestStatus_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<[_WithdrawalRequest, _RequestStatus]>]): [Principal, Array<[WithdrawalRequest, RequestStatus]>] {
    return [
        value[0],
        from_candid_vec_n29(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_WithdrawalRequest, _RequestStatus]): [WithdrawalRequest, RequestStatus] {
    return [
        value[0],
        from_candid_RequestStatus_n26(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: _Time;
} | {
    rejected: _Time;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "approved";
    approved: Time;
} | {
    __kind__: "rejected";
    rejected: Time;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "approved" in value ? {
        __kind__: "approved",
        approved: value.approved
    } : "rejected" in value ? {
        __kind__: "rejected",
        rejected: value.rejected
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    withdraw: null;
} | {
    p2pReceive: Principal;
} | {
    deposit: null;
} | {
    p2pSend: Principal;
}): {
    __kind__: "withdraw";
    withdraw: null;
} | {
    __kind__: "p2pReceive";
    p2pReceive: Principal;
} | {
    __kind__: "deposit";
    deposit: null;
} | {
    __kind__: "p2pSend";
    p2pSend: Principal;
} {
    return "withdraw" in value ? {
        __kind__: "withdraw",
        withdraw: value.withdraw
    } : "p2pReceive" in value ? {
        __kind__: "p2pReceive",
        p2pReceive: value.p2pReceive
    } : "deposit" in value ? {
        __kind__: "deposit",
        deposit: value.deposit
    } : "p2pSend" in value ? {
        __kind__: "p2pSend",
        p2pSend: value.p2pSend
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingApiActivation>): Array<PendingApiActivation> {
    return value.map((x)=>from_candid_PendingApiActivation_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<[_DepositRequest, _RequestStatus]>]>): Array<[Principal, Array<[DepositRequest, RequestStatus]>]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_DepositRequest, _RequestStatus]>): Array<[DepositRequest, RequestStatus]> {
    return value.map((x)=>from_candid_tuple_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<[_WithdrawalRequest, _RequestStatus]>]>): Array<[Principal, Array<[WithdrawalRequest, RequestStatus]>]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_WithdrawalRequest, _RequestStatus]>): Array<[WithdrawalRequest, RequestStatus]> {
    return value.map((x)=>from_candid_tuple_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiActivationRequest>): Array<ApiActivationRequest> {
    return value.map((x)=>from_candid_ApiActivationRequest_n19(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    const backend = new Backend(actor, _uploadFile, _downloadFile, options.processError);
    // Proxy: fall through to raw ICP actor for methods not implemented in Backend class
    // This permanently fixes all (actor as any).functionName() calls for functions like
    // joinChatQueue, adminGetAllUserDetails, sendChatMessage, etc.
    return new Proxy(backend, {
        get(target: Backend, prop: string | symbol, receiver: unknown) {
            const val = Reflect.get(target, prop, receiver);
            if (val !== undefined) return val;
            const rawVal = (actor as Record<string | symbol, unknown>)[prop];
            if (typeof rawVal === 'function') return (rawVal as (...args: unknown[]) => unknown).bind(actor);
            return rawVal;
        }
    }) as Backend;
}
